### ISSUE TITLE
Внезапный код

### ISSUE THREAD

**Issue by Puppollo** [Ow192/epixphp#8]
```
    exits($_POST["quit"]);
    $tokenscheck=tokencheck();
    $searching="";
```

Как понять этот участок кода не читая код функции?
Код должен быть максимально понятным даже для сторонних разработчиков. Сейчас смотря на этот участок я вижу что код на вызове функции exits наверное должен завершить свою работу, но вместо этого далее идет проверка токена.

**Comment by Ow192** [comment]
переименовал (check_exit_button) и вынес за пределы case
